name             'cafe-data'
maintainer       'Evan Sosenko'
maintainer_email 'razorx@evansosenko.com'
license          'Apache 2.0'
description      'OpsCafe database and storage infrastructure.'
source_url       'https://github.com/opscafe/data'
issues_url       'https://github.com/opscafe/data/issues'
version          '0.0.0'

recipe 'cafe-data::default', 'Installs and configures a data server.'
